import { createEnv } from "@t3-oss/env-nextjs";
import { z } from "zod";

export const env = createEnv({
  server: {
    DATABASE_URL: z.string().min(1),
    BASE_URL: z.string().min(1),
    BETTER_AUTH_SECRET: z.string().min(1),
    GITHUB_CLIENT_ID: z.string().min(1),
    GITHUB_CLIENT_SECRET: z.string().min(1),
    GOOGLE_CLIENT_ID: z.string().min(1),
    GOOGLE_CLIENT_SECRET: z.string().min(1),
    DISCORD_CLIENT_ID: z.string().min(1),
    DISCORD_CLIENT_SECRET: z.string().min(1),
    RESEND_API_KEY: z.string().min(1),
    UPLOADTHING_SECRET: z.string().min(1),
    UPLOADTHING_TOKEN: z.string().min(1),
    OPENAI_API_KEY: z.string().min(1),
    ANTHROPIC_API_KEY: z.string().min(1),
    MAILCHIMP_LIST_ID: z.string().min(1),
    MAILCHIMP_API_KEY: z.string().min(1),
    PLACID_PRIVATE_TOKEN: z.string().min(1),
  },
  createFinalSchema: (env) => {
    return z.object(env).transform((val) => {
      const {
        DATABASE_URL,
        BASE_URL,
        BETTER_AUTH_SECRET,
        GITHUB_CLIENT_ID,
        GITHUB_CLIENT_SECRET,
        GOOGLE_CLIENT_ID,
        GOOGLE_CLIENT_SECRET,
        DISCORD_CLIENT_ID,
        DISCORD_CLIENT_SECRET,
        RESEND_API_KEY,
        UPLOADTHING_SECRET,
        UPLOADTHING_TOKEN,
        OPENAI_API_KEY,
        ANTHROPIC_API_KEY,
        MAILCHIMP_LIST_ID,
        MAILCHIMP_API_KEY,
        PLACID_PRIVATE_TOKEN,
        ...rest
      } = val;
      return {
        ...rest,
        DATABASE_URL,
        BASE_URL,
        BETTER_AUTH_SECRET,
        GITHUB_CLIENT_ID,
        GITHUB_CLIENT_SECRET,
        GOOGLE_CLIENT_ID,
        GOOGLE_CLIENT_SECRET,
        DISCORD_CLIENT_ID,
        DISCORD_CLIENT_SECRET,
        RESEND_API_KEY,
        UPLOADTHING_SECRET,
        UPLOADTHING_TOKEN,
        OPENAI_API_KEY,
        ANTHROPIC_API_KEY,
        MAILCHIMP_LIST_ID,
        MAILCHIMP_API_KEY,
        PLACID_PRIVATE_TOKEN,
      };
    });
  },
  emptyStringAsUndefined: true,
  experimental__runtimeEnv: {
    DATABASE_URL: process.env.DATABASE_URL,
    BASE_URL: process.env.BASE_URL,
    BETTER_AUTH_SECRET: process.env.BETTER_AUTH_SECRET,
    GITHUB_CLIENT_ID: process.env.GITHUB_CLIENT_ID,
    GITHUB_CLIENT_SECRET: process.env.GITHUB_CLIENT_SECRET,
    GOOGLE_CLIENT_ID: process.env.GOOGLE_CLIENT_ID,
    GOOGLE_CLIENT_SECRET: process.env.GOOGLE_CLIENT_SECRET,
    DISCORD_CLIENT_ID: process.env.DISCORD_CLIENT_ID,
    DISCORD_CLIENT_SECRET: process.env.DISCORD_CLIENT_SECRET,
    RESEND_API_KEY: process.env.RESEND_API_KEY,
    UPLOADTHING_SECRET: process.env.UPLOADTHING_SECRET,
    UPLOADTHING_TOKEN: process.env.UPLOADTHING_TOKEN,
    OPENAI_API_KEY: process.env.OPENAI_API_KEY,
    ANTHROPIC_API_KEY: process.env.ANTHROPIC_API_KEY,
    MAILCHIMP_LIST_ID: process.env.MAILCHIMP_LIST_ID,
    MAILCHIMP_API_KEY: process.env.MAILCHIMP_API_KEY,
    PLACID_PRIVATE_TOKEN: process.env.PLACID_PRIVATE_TOKEN,
  },
});
